### ISSUE TITLE
signal file use bug

### ISSUE THREAD

**Issue by qweszxc7410** [mtkresearch/generative-fusion-decoding#2]
1.the numpy version should be lower then 2.0.0 but requirements.txt not define 
pip install 'numpy<2'

2. the sigal file use command can run as follows,the original command less  config_files/model/gfd-asr-zhtw.yaml 
python benchmarks/run_single_file.py --config_file_path config_files/model/gfd-asr-zhtw.yaml --audio_file_path test.mp3 --result_output_path output.txt

**Comment by Splend1d** [comment]
Thank you for your reminder.

We hope that we have fully resolved it from testing on Kaggle!

https://www.kaggle.com/code/a24998667/generative-fusion-decoding-example
